### ISSUE TITLE
excludeFields of pieces with joins ends up responding with the data from the piece without the _joins

### ISSUE THREAD

**Issue by pietro-rutzen** [apostrophecms/apostrophe-headless#36]
Example: 
https://gramadosummit.com/api/v1/lectures

Has a _speaker join.

But when getting thata from https://gramadosummit.com/api/v1/lectures?excludeFields=type,slug,createdAt,updatedAt,titleSortified,highSearchText,highSearchWords,lowSearchText,searchSummary,docPermissions,_originalWidgets,siteMapPriority,userId,tags 

That join vanishes from the object.

**Comment by boutell** [comment]
Hi Pietro, we just published a new release that addresses this. In a way, it was not a bug. But it is confusing and not obvious that excluding `type` from the mongo query impacts joins for internal Apostrophe reasons. So we changed it so that `type` is deleted from the objects at the end but included in the initial query.
